const express = require('express')
const router = express.Router()
const { login, protect, updateMe, sendMe,updateEmail,forgotPassword } = require("../../controllers/admin/adminControllers")
const { uploadImage } = require('../../controllers/admin/bannerControllers')
const { uploadProductImage, deleteProductImage } = require('../../controllers/admin/productsControllers')
const { getAboutus, editAboutus } = require('../../controllers/admin/aboutUsController')
router.post("/login", login)
router.patch("/",  protect,updateMe)
router.patch("/email",  protect,updateEmail)
// router.patch("/message",  updateMessage)
router.get("/",protect,  sendMe)
router.patch("/forgot-password", forgotPassword)
router.post("/upload-image",uploadImage)
router.post("/multiple-image",uploadProductImage)
router.delete("/image/:id",deleteProductImage)
router.get("/about-us",getAboutus)
router.patch("/about-us",editAboutus)
router.use("/banners",  require("./routes/bannersRouter")) //test edildi
router.use('/categories',  require('./routes/categoriesRouter')); //test etmeli)
router.use("/subcategories",  require("./routes/subcategoriesRouter")) //test etmeli
router.use("/service-categories",require("./routes/servicecategoriesRouter"))
router.use("/services",require("./routes/serviceRouter"))
router.use("/brands",  require("./routes/brandsRouter")) //test etmeli
router.use("/sizes",require("./routes/sizesRouter"))
router.use("/colors",require("./routes/colorRouter"))
router.use("/products",  require("./routes/productsRouter")) //test etmeli
router.use("/orders", require("./routes/ordersRouter"))
router.use("/news",require("./routes/newsRouter"))
router.use("/awards",require("./routes/awardsRouter"))
router.use("/clients",require("./routes/clientsRouter"))
router.use("/workers",require("./routes/workersRouter"))
router.use("/achievements",require("./routes/achievementsRouter"))
router.use("/mails",require("./routes/mailsRouter"))
module.exports = router